apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-app-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/james-rotary/hello-world-app-config-kustomize.git
    targetRevision: HEAD
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
