apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  selector:
    matchLabels:
      app: hello-world-app
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
      - name: hello-world-app
        image: hello-world-app:dev-remote
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: storage
          mountPath: /mnt/storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: hello-world-pvc
